// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzzowacrsgpxxhjvmpob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6em93YWNyc2dweHhoanZtcG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTk5MDUsImV4cCI6MjA3MjAzNTkwNX0.NCbfrrqgCseB0ClQFzViEzhXYvEVl1sKjbEBQ_YUmWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});